import Head from 'next/head'
import Banner from '../components/banner/Banner'
import Faq from '../components/faq/Faq'
import Features from '../components/features/Features'
import Footer from '../components/footer/Footer'
import Navbar from '../components/navbar/Navbar'
import Newsletter from '../components/newsletter/Newsletter'
import Pricing from '../components/pricing/Pricing'
import Proud from '../components/proud/Proud'
import Revenue from '../components/revenue/Revenue'
import Team from '../components/Team/Team'

export default function Home() {
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <Features />
      <Revenue />
      <Team />
      <Proud />
      <Newsletter />
      <Pricing />
      <Faq />
      <Footer />
    </div>
  )
}
